### PR TITLE
Feature: More on GitHub badge 🎉

### PR DESCRIPTION
**Pull request by thinkverse**
I thought about creating a whole repo for this but remembered that @puf17640 had `git-badges` 🔥

## Feature
Traveling to the endpoint `years/:user` returns an `SVG` with the number of years a user has been a member.

### Usage
To use this feature, two environmental variables need to be added `GITHUB_ID` and `GITHUB_TOKEN`.
Since we aren't hitting the GitHub API with OAuth we're using personal tokens to up the rate limit.
```bash
GITHUB_ID=username
GITHUB_TOKEN=personal_token
```

### Enhancements
Enhancements that could be made are caching the result from the GitHub API to limit the number of requests being made,
the current rate limit is 5000 requests per hour thanks to the Basic Auth - more info available on the [GitHub Docs](https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api#authentication), might be good for the time being though. 🤔

---

Any feedback is much appreciated, and any help with the code would be awesome. 😀 👍

### CODE REVIEW

**Comment by thinkverse** [comment]
@puf17640 Actually removing `date-fns` and using your method doesn't show the correct years, it shows the difference between the calendar year, not the year between the two dates, my year badge should say `7` and I get `8`.

**Comment by puf17640** [comment]
> @puf17640 Actually removing `date-fns` and using your method doesn't show the correct year, it shows the difference between the calendar year, not the year between the two dates, my year badge should say `7` and I get `8`.

Good point, didn't think too much about it, I was about to try out if there are differences in having date-fns or not, will add it back in now! You also gave me the idea to have a few other badges that show profile info, will add them in right now too!

**Comment by puf17640** [comment]
`/repos/:user` now returns the count of public repos

**Comment by thinkverse** [comment]
Please don't force push, it's causing merge conflicts. 👍

**Comment by puf17640** [comment]
> Please don't force push, it's causing merge conflicts. 👍

I forced push over your readability/whitespace commit as I already ran `lint:fix` which fixed the whitespaces and I don't think newlines are needed since readability is pretty okay imo

**Pull request merged**
